import Head from 'next/head'
import styles from 'styles/pages/home.module.scss'
import { Row, Col } from 'react-bootstrap'

export default function About() {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="About Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Row>
          <Col className="text-center py-2">
            <h1 className={styles.title}>About</h1>
          </Col>
        </Row>
      </main>
    </div>
  )
}
