import Head from 'next/head'
import styles from 'styles/pages/home.module.scss'
import { Container, Row, Col } from 'react-bootstrap'

export default function Home() {
  return (
    <div>
      <Head>
        <title>nextjs-toolkit-pwa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container fluid>
          <Row>
            <Col className='text-center py-2'>
              <h1 className={styles.title}>Hello World</h1>
              <h2 className={styles.subtitle}>welcome</h2>
            </Col>
          </Row>
        </Container>
      </main>
    </div>
  )
}
